export enum ACCOUNT_LN {
  //account-security
  TXT_CHANGE_PASSWORD = "TXT_CHANGE_PASSWORD",
  TXT_OLD_PASSWORD = "TXT_OLD_PASSWORD",
  TXT_NEW_PASSWORD = "TXT_NEW_PASSWORD",
  TXT_CONFIRM_PASSWORD = "TXT_CONFIRM_PASSWORD",
  TXT_RESET = "TXT_RESET",
  TXT_SAVE_CHANGES = "TXT_SAVE_CHANGES",
  TXT_OLD_PASSWORD_REQUIRED = "TXT_OLD_PASSWORD_REQUIRED",
  TXT_PASSWORD_REQUIRED = "TXT_PASSWORD_REQUIRED",
  TXT_PASSWORD_6_LETTERS = "TXT_PASSWORD_6_LETTERS",
  TXT_PASSWORD_MAX12_LETTERS = "TXT_PASSWORD_MAX12_LETTERS",
  TXT_RETYPE_PASSWORD = "TXT_RETYPE_PASSWORD",
  TXT_CONFIRM_PASSWORD_NOTMATCH = "TXT_CONFIRM_PASSWORD_NOTMATCH",
  TXT_PASSWORD_CHANGED="TXT_PASSWORD_CHANGED",
  TXT_PASSWORD_SAME_AS_OLD="TXT_PASSWORD_SAME_AS_OLD",

  //manage-profile
  TXT_FIRST_NAME = "TXT_FIRST_NAME",
  TXT_MIDDLE_NAME = "TXT_MIDDLE_NAME",
  TXT_LAST_NAME = "TXT_LAST_NAME",
  TXT_EMAIL_IDO = "TXT_OFFICIAL_EMAIL_ID",
  TXT_MOBILE_NO = "TXT_MOBILE_NO",
  TXT_UPLOAD_NEW_PICTURE = "TXT_UPLOAD_NEW_PICTURE",
  TXT_REMOVE_PICTURE = "TXT_REMOVE_PICTURE",
  TXT_FIELD_REQUIRED = "TXT_FIELD_REQUIRED",
  TXT_MINIMUM_10_DIGITS = "TXT_MINIMUM_10_DIGITS",

  //organisational-profile
  TXT_COMPANY_NAME = "TXT_COMPANY_NAME",
  TXT_SHORT_NAME = "TXT_SHORT_NAME",
  TXT_COUNTRY = "TXT_COUNTRY",
  TXT_COMPANY_URL = "TXT_COMPANY_URL",
  TXT_STATE = "TXT_STATE",
  TXT_CITY = "TXT_CITY",
  TXT_INDUSTRY = "TXT_INDUSTRY",
  TXT_ACCOUNT_TYPE = "TXT_ACCOUNT_TYPE",
  TXT_STAF_REC = "TXT_STAFFING_AND_RECRUITING",
  TXT_CORPORATE = "TXT_CORPORATE",
  TXT_SHORT_NAME_MAX15 = "TXT_SHORT_NAME_MAX15",
  TXT_SHORT_NAME_MIN5 = "TXT_SHORT_NAME_MIN5",

  //account
  TXT_MANAGE_PROFILE = "TXT_MANAGE_PROFILE",
  TXT_PERSONAL_PROFILE = "TXT_PERSONAL_PROFILE",
  TXT_ORG_PROFILE = "TXT_ORGANISATION_PROFILE",
  TXT_ACCOUNT_SECURITY = "TXT_ACCOUNT_SECURITY",
  TXT_UPLOAD_MANAGE_ACCOUNT = "TXT_UPLOAD_MANAGE_ACCOUNT",
}
