export enum ACCOUNT_LN {
  //account-security
  TXT_CHANGE_PASSWORD = "TXT_CHANGE_PASSWORD",
  TXT_OLD_PASSWORD = "TXT_OLD_PASSWORD",
  TXT_NEW_PASSWORD = "TXT_NEW_PASSWORD",
  TXT_CONFIRM_PASSWORD = "TXT_CONFIRM_PASSWORD",
  TXT_RESET = "TXT_RESET",
  TXT_SAVE_CHANGES = "TXT_SAVE_CHANGES",

  //manage-profile
  TXT_FIRST_NAME = "TXT_FIRST_NAME",
  TXT_MIDDLE_NAME = "TXT_MIDDLE_NAME",
  TXT_LAST_NAME = "TXT_LAST_NAME",
  TXT_EMAIL_IDO = "TXT_EMAIL_IDO",
  TXT_MOBILE_NO = "TXT_MOBILE_NO",
  TXT_UPLOAD_NEW_PICTURE = "TXT_UPLOAD_NEW_PICTURE",
  TXT_REMOVE_PICTURE = "TXT_REMOVE_PICTURE",

  //organisational-profile
  TXT_COMPANY_NAME = "TXT_COMPANY_NAME",
  TXT_SHORT_NAME = "TXT_SHORT_NAME",
  TXT_COUNTRY = "TXT_COUNTRY",
  TXT_COMPANY_URL = "TXT_COMPANY_URL",
  TXT_STATE = "TXT_STATE",
  TXT_CITY = "TXT_CITY",
  TXT_INDUSTRY = "TXT_INDUSTRY",
  TXT_ACCOUNT_TYPE = "TXT_ACCOUNT_TYPE",
  TXT_STAF_REC = "TXT_STAF_REC",
  TXT_CORPORATE = "TXT_CORPORATE",

  //account
  TXT_MANAGE_PROFILE = "TXT_MANAGE_PROFILE",
  TXT_PERSONAL_PROFILE = "TXT_PERSONAL_PROFILE",
  TXT_ORG_PROFILE = "TXT_ORG_PROFILE",
  TXT_ACCOUNT_SECURITY = "TXT_ACCOUNT_SECURITY",
}