//settings-menu
export enum SETTINGS_LN {
  TXT_SETTINGS = "TXT_SETTINGS",
  TXT_PERMISSIONS = "TXT_PERMISSIONS",
  TXT_MANAGE_LEVEL_ACCESS = "TXT_MANAGE_LEVEL_ACCESS",
  TXT_TEMPLATE = "TXT_TEMPLATE",
  TXT_SET_ = "TXT_SET_",
  TXT_FORM_VISIBILITY_SETTING = "TXT_FORM_VSIBILITY_SETTINGS",
  TXT_CUSTOMISE_WORKFLOW = "TXT_CUSTOMISE_WORKFLOW",
  TXT_INTEGRATION = "TXT_INTEGRATION",
  TXT_EDIT_PERSONAL_INFO_COMMUNICATION_PREFERENCES = "TXT_EDIT_PERSONAL_INFO_COMMUNICATION_PREFERENCES",
  TXT_CONFIGURATION = "TXT_CONFIGURATION",
  TXT_MANAGE_ADVERTISING = "TXT_MANAGE_ADVERTISING",
  TXT_BILLING = "TXT_BILLING",
  TXT_PURCHASE_HISTORY_PAYMENT_DETAILS = "TXT_PURCHASE_HISTORY_PAYMENT_DETAILS",
  TXT_CANDIDATE_PORTAL = "TXT_CANDIDATE_PORTAL",
  TXT_EDIT_COMPANY_INFO_ROLES_CONTRACTS = "TXT_EDIT_COMPANY_INFO_ROLES_CONTRACTS",
  TXT_VENDOR_PORTAL = "TXT_VENDOR_PORTAL",
  TXT_EMPLOYEE_PORTAL = "TXT_EMPLOYEE_PORTAL",
  TXT_CAREER_PAGE_BUILDER = "TXT_CAREER_PAGE_BUILDER",
  TXT_GDPR = "TXT_GDPR",

  //permission > add-role
  TXT_CREATE_NEW_ROLE = "TXT_CREATE_NEW_ROLE",
  TXT_UPDATE_ROLE = "TXT_UPDATE_ROLE",
  TXT_ROLE_TYPE = "TXT_ROLE_TYPE",
  TXT_NEW_ROLE_NAME = "TXT_NEW_ROLE_NAME",
  TXT_SHOW_ALL_PERMISSIONS = "TXT_SHOW_ALL_PERMISSIONS",
  TXT_FIELD_REQUIRED = "TXT_FIELD_REQUIRED",

  //permission > add-user
  TXT_ADD_USER = "TXT_ADD_USER",
  TXT_FIRST_NAME = "TXT_FIRST_NAME",
  TXT_MIDDLE_NAME = "TXT_MIDDLE_NAME",
  TXT_LAST_NAME = "TXT_LAST_NAME",
  TXT_USER_ROLE = "TXT_USER_ROLE",
  TXT_DESIGNATION = "TXT_DESIGNATION",
  TXT_BUSINESS_VERTICAL = "TXT_BUSINESS_VERTICAL",
  TXT_PRACTICE = "TXT_PRACTICE",
  TXT_LOCATION = "TXT_LOCATION",
  TXT_REPORTING_MANAGER = "TXT_REPORTING_MANAGER",
  TXT_RESET = "TXT_RESET",
  TXT_INVITE = "TXT_INVITE",
  TXT_FIRST_NAME_REQUIRED = "TXT_FIRST_NAME_REQUIRED",
  TXT_FIRST_NAME_3ATLEAST_LETTERS = "TXT_FIRST_NAME_3ATLEAST_LETTERS",
  TXT_FIRST_NAME_20MAX_LETTERS = "TXT_FIRST_NAME_20MAX_LETTERS",
  TXT_MIDDLE_NAME_3_LETTERS = "TXT_MIDDLE_NAME_3_LETTERS",
  TXT_MIDDLE_NAME_20_LETTERS = "TXT_MIDDLE_NAME_20_LETTERS",
  TXT_LAST_NAME_REQUIRED = "TXT_LAST_NAME_REQUIRED",
  TXT_LAST_NAME_3_LETTERS = "TXT_LAST_NAME_3_LETTERS",
  TXT_FIRST_NAME_20_LETTERS = "TXT_FIRST_NAME_20_LETTERS",
  TXT_EMAIL_REQUIRED = "TXT_EMAIL_REQUIRED",
  TXT_EMAIL_NOT_VALID = "TXT_EMAIL_NOT_VALID",

  //permission > m-filter
  TXT_FILTERS = "TXT_FILTERS",
  TXT_APPLY = "TXT_APPLY",
  TXT_SORT_BY = "TXT_SORT_BY",
  TXT_BY_STATUS = "TXT_BY_STATUS",
  TXT_BY_ROLE = "TXT_BY_ROLE",
  TXT_SORT_BY_STATUS = "TXT_SORT_BY_STATUS",

  //permission > user-detail
  TXT_EDIT_INFO = "TXT_EDIT_INFORMATION",
  TXT_ADMIN = "TXT_ADMIN",
  TXT_USER_DETAILS = "TXT_USER DETAILS",
  TXT_PHONE = "TXT_PHONE",
  TXT_CANCEL = "TXT_CANCEL",
  TXT_UPDATE = "TXT_UPDATE",

  //permissions > user-manage
  TXT_USER_MANAGEMENT = "TXT_USER_MANAGEMENT",
  TXT_USER_SELECTED = "TXT_USER_SELECTED",
  TXT_USERS_SELECTED = "TXT_USERS_SELECTED",
  TXT_ACTIVATE = "TXT_ACTIVATE",
  TXT_ACTIVE = "TXT_ACTIVE",
  TXT_DEACTIVATE = "TXT_DEACTIVATE",
  TXT_DELETE = "TXT_DELETE",
  TXT_TOTAL_USERS = "TXT_TOTAL_USERS",
  TXT_TOTAL_USER = "TXT_TOTAL_USER",
  TXT_FULL_NAME = "TXT_FULL_NAME",
  TXT_ROLE = "TXT_ROLE",
  TXT_EMAIL = "TXT_EMAIL",
  TXT_STATUS = "TXT_STATUS",
  TXT_PENDING = "TXT_PENDING",
  TXT_INACTIVE = "",
  TXT_LAST_UPDATED = "TXT_LAST_UPDATED",
  TXT_UPDATED = "TXT_UPDATED",
  TXT_VIEW_PERMISSION = "TXT_VIEW_PERMISSION",
  TXT_VIEW_DETAILS = "TXT_VIEW_DETAILS",
  TXT_EDIT_USER = "TXT_EDIT_USER",
  TXT_ACTIVATE_USER = "TXT_ACTIVATE_USER",
  TXT_DEACTIVATE_USER = "TXT_DEACTIVATE_USER",
  TXT_DELETE_USER = "TXT_DELETE_USER",
  TXT_PDF = "TXT_PDF",
  TXT_EXCEL = "TXT_EXCEL",
  TXT_CSV = "TXT_CSV",
  TXT_EXPORT = "TXT_EXPORT",
  TXT_ALL = "TXT_ALL",
  TXT_DEACTIVE = "TXT_DEACTIVE",

  //permissions > view-role
  TXT_ACCOUNT_ROLE = "TXT_ACCOUNT_ROLE",
  TXT_ACCOUNTS_ROLES = "TXT_ACCOUNT_ROLES",
  TXT_LAST_EDITED = "TXT_LAST_EDITED",
  TXT_EDIT = "TXT_EDIT",
  TXT_VIEW = "TXT_VIEW",
  TXT_NEW_ROLE = "TXT_NEW_ROLE",
  TXT_SORT_BY_ADDED_ROLE_NAME = "TXT_SORT_BY_ADDED_ROLE_NAME",
  TXT_SORT_BY_ADDED_USER_COUNT = "TXT_SORT_BY_ADDED_USER_COUNT",
  TXT_SORT_BY_ADDED_LAST_UPDATED = "TXT_SORT_BY_ADDED_LAST_UPDATED",
}

// export default ln = Translator(SETTINGS_LN)
// export obj = {
//   TXT_CSV : 'TXT_CSV'
// }

// import { TranslatePipe} from '@mucrest/ng-core'

// var translatePipe = new TranslatePipe;

// translatePipe.transform()
